title: 5ky1s61ue's Blog
description: Try to be a hacker, hack in mylife and take control of it.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github: 
  repository_url: https://github.com/5ky1s61ue
